from __future__ import annotations

from dataclasses import dataclass, field
from hashlib import sha256
import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from .models import ActionRequest

CLASS_WEIGHTS = {
    "core": 30,
    "core_candidate": 28,
    "core_promotion_gate": 26,
    "optional_core": 16,
    "optional": 8,
    "experimental": 4,
    "legacy": -25,
}

SIGNAL_WEIGHTS = {
    "runtime_integration_gap": 28,
    "spec_only": 20,
    "missing_tests": 14,
    "missing_adapter": 14,
    "production_blocker": 22,
    "duplicate_role": 5,
    "stale_reference": 5,
    "already_integrated": -20,
    "legacy": -30,
    "archived": -60,
}

TASK_BY_SIGNAL = (
    ("production_blocker", "production_gap"),
    ("runtime_integration_gap", "integration_adapter"),
    ("spec_only", "implementation_gap"),
    ("missing_tests", "test_gap"),
    ("missing_adapter", "adapter_gap"),
    ("duplicate_role", "consolidation_review"),
)


@dataclass(frozen=True, slots=True)
class RepoObservation:
    full_name: str
    repo_class: str = "optional"
    maturity: str = "unknown"
    size_kb: int = 0
    archived: bool = False
    signals: tuple[str, ...] = field(default_factory=tuple)
    evidence: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if not self.full_name.strip():
            raise ValueError("full_name is required")
        object.__setattr__(self, "signals", tuple(dict.fromkeys(self.signals)))
        object.__setattr__(self, "evidence", tuple(self.evidence))


@dataclass(frozen=True, slots=True)
class MaintenanceCandidate:
    full_name: str
    score: int
    task_type: str
    title: str
    rationale: str
    evidence: tuple[str, ...]
    requested_capability: str = "github.issue.create"
    requested_action: str = "create_issue"
    route: str = "REVIEW"

    def to_action_request(self, *, request_id: str) -> ActionRequest:
        body_lines = [self.rationale]
        if self.evidence:
            body_lines.extend(["", "Evidence:", *[f"- {item}" for item in self.evidence]])
        body_lines.extend([
            "",
            f"Maintainer score: {self.score}",
            "Generated by Personal Agent Runtime Repo Maintainer. Human review required.",
        ])
        return ActionRequest(
            request_id=request_id,
            capability=self.requested_capability,
            action=self.requested_action,
            resource=self.full_name,
            payload={"title": self.title, "body": "\n".join(body_lines)},
            actor="repo-maintainer-agent",
        )


@dataclass(frozen=True, slots=True)
class MaintenanceReceipt:
    receipt_version: str
    snapshot_id: str
    observed_repositories: int
    selected: tuple[MaintenanceCandidate, ...]
    input_digest: str
    receipt_hash: str

    def as_dict(self) -> dict:
        return {
            "receipt_version": self.receipt_version,
            "snapshot_id": self.snapshot_id,
            "observed_repositories": self.observed_repositories,
            "selected": [
                {
                    "full_name": c.full_name,
                    "score": c.score,
                    "task_type": c.task_type,
                    "title": c.title,
                    "rationale": c.rationale,
                    "evidence": list(c.evidence),
                    "requested_capability": c.requested_capability,
                    "requested_action": c.requested_action,
                    "route": c.route,
                }
                for c in self.selected
            ],
            "input_digest": self.input_digest,
            "receipt_hash": self.receipt_hash,
        }


class RepoMaintainer:
    """Deterministic repository triage. It proposes work; it does not grant write authority."""

    def select(self, observations: Sequence[RepoObservation], *, limit: int = 3) -> tuple[MaintenanceCandidate, ...]:
        if limit < 1:
            raise ValueError("limit must be >= 1")
        candidates = [self._candidate(obs) for obs in observations if not obs.archived]
        candidates.sort(key=lambda item: (-item.score, item.full_name.lower()))
        return tuple(candidates[:limit])

    def build_receipt(
        self,
        observations: Sequence[RepoObservation],
        *,
        snapshot_id: str,
        limit: int = 3,
    ) -> MaintenanceReceipt:
        selected = self.select(observations, limit=limit)
        canonical_input = [
            {
                "full_name": o.full_name,
                "repo_class": o.repo_class,
                "maturity": o.maturity,
                "size_kb": o.size_kb,
                "archived": o.archived,
                "signals": list(o.signals),
                "evidence": list(o.evidence),
            }
            for o in sorted(observations, key=lambda x: x.full_name.lower())
        ]
        input_digest = sha256(
            json.dumps(canonical_input, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        payload = {
            "receipt_version": "0.5",
            "snapshot_id": snapshot_id,
            "observed_repositories": len(observations),
            "selected": [
                {"full_name": c.full_name, "score": c.score, "task_type": c.task_type}
                for c in selected
            ],
            "input_digest": input_digest,
        }
        receipt_hash = sha256(
            json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        return MaintenanceReceipt(
            receipt_version="0.5",
            snapshot_id=snapshot_id,
            observed_repositories=len(observations),
            selected=selected,
            input_digest=input_digest,
            receipt_hash=receipt_hash,
        )

    def _candidate(self, obs: RepoObservation) -> MaintenanceCandidate:
        score = CLASS_WEIGHTS.get(obs.repo_class, 0)
        score += sum(SIGNAL_WEIGHTS.get(signal, 0) for signal in obs.signals)
        if obs.archived:
            score += SIGNAL_WEIGHTS["archived"]
        task_type = "maintenance_review"
        for signal, mapped in TASK_BY_SIGNAL:
            if signal in obs.signals:
                task_type = mapped
                break

        repo_short = obs.full_name.split("/", 1)[-1]
        title = self._title(repo_short, task_type)
        signal_text = ", ".join(obs.signals) if obs.signals else "no explicit maintenance signal"
        rationale = (
            f"{repo_short} is classified as {obs.repo_class} with maturity '{obs.maturity}'. "
            f"Observed maintenance signals: {signal_text}. "
            "Create a reviewable maintenance task; do not modify the repository automatically."
        )
        return MaintenanceCandidate(
            full_name=obs.full_name,
            score=score,
            task_type=task_type,
            title=title,
            rationale=rationale,
            evidence=obs.evidence,
        )

    @staticmethod
    def _title(repo_short: str, task_type: str) -> str:
        labels = {
            "production_gap": "Close production-readiness gap",
            "integration_adapter": "Add Personal Agent Runtime integration adapter",
            "implementation_gap": "Implement the documented core contract",
            "test_gap": "Add regression coverage for core invariants",
            "adapter_gap": "Add missing adapter contract",
            "consolidation_review": "Review overlap and consolidation path",
            "maintenance_review": "Review next maintenance step",
        }
        return f"[Repo Maintainer] {labels[task_type]} — {repo_short}"


def load_repo_snapshot(path: Path) -> tuple[str, tuple[RepoObservation, ...]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    snapshot_id = str(data.get("snapshot_id", "snapshot-unknown"))
    repos = tuple(
        RepoObservation(
            full_name=item["full_name"],
            repo_class=item.get("repo_class", "optional"),
            maturity=item.get("maturity", "unknown"),
            size_kb=int(item.get("size_kb", 0)),
            archived=bool(item.get("archived", False)),
            signals=tuple(item.get("signals", ())),
            evidence=tuple(item.get("evidence", ())),
        )
        for item in data["repositories"]
    )
    return snapshot_id, repos
